owner: iuc
name: fcs_txt_merge_downsample
description: Merge and downsample txt-converted FCS files into one text file based on headers 
long_description: |
    **Input**
    This tool uses valid FCS files as input.

    **Output file**
    FCS file summary includes number of events, list of markers and parameters, and summary statistics for each.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/fcs_summary
type: unrestricted
