owner: Cristel Thomas
name: upload_files
description: upload files including those with an fcs extension
long_description: |
    **Input**
    One or more files
    
    **Output**
    Files loaded in history 
    
    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy/tree/master/tools/data_source/
type: unrestricted
