owner: Cristel Thomas
name: upload_files
description: upload files from your computer
long_description: |
    **Input**
    One or more files
    
    **Output**
    Files loaded in history 
    
    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/AstraZeneca-Omics/immport-galaxy-tools/tree/master/flowtools/upload_files
type: unrestricted
